#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BestSellers.Droid.Resource", IsApplication=true)]

namespace BestSellers.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Android.Dialog.Resource.Drawable.dialog_disclosure = BestSellers.Droid.Resource.Drawable.dialog_disclosure;
			Android.Dialog.Resource.Drawable.expander_ic_minimized = BestSellers.Droid.Resource.Drawable.expander_ic_minimized;
			Android.Dialog.Resource.Id.dialog_BoolField = BestSellers.Droid.Resource.Id.dialog_BoolField;
			Android.Dialog.Resource.Id.dialog_Button = BestSellers.Droid.Resource.Id.dialog_Button;
			Android.Dialog.Resource.Id.dialog_DisclosureField = BestSellers.Droid.Resource.Id.dialog_DisclosureField;
			Android.Dialog.Resource.Id.dialog_HtmlField = BestSellers.Droid.Resource.Id.dialog_HtmlField;
			Android.Dialog.Resource.Id.dialog_ImageLeft = BestSellers.Droid.Resource.Id.dialog_ImageLeft;
			Android.Dialog.Resource.Id.dialog_ImageRight = BestSellers.Droid.Resource.Id.dialog_ImageRight;
			Android.Dialog.Resource.Id.dialog_LabelField = BestSellers.Droid.Resource.Id.dialog_LabelField;
			Android.Dialog.Resource.Id.dialog_LabelPercentageField = BestSellers.Droid.Resource.Id.dialog_LabelPercentageField;
			Android.Dialog.Resource.Id.dialog_LabelSubtextField = BestSellers.Droid.Resource.Id.dialog_LabelSubtextField;
			Android.Dialog.Resource.Id.dialog_Panel = BestSellers.Droid.Resource.Id.dialog_Panel;
			Android.Dialog.Resource.Id.dialog_RadioButtonList = BestSellers.Droid.Resource.Id.dialog_RadioButtonList;
			Android.Dialog.Resource.Id.dialog_SliderField = BestSellers.Droid.Resource.Id.dialog_SliderField;
			Android.Dialog.Resource.Id.dialog_Spinner = BestSellers.Droid.Resource.Id.dialog_Spinner;
			Android.Dialog.Resource.Id.dialog_ValueField = BestSellers.Droid.Resource.Id.dialog_ValueField;
			Android.Dialog.Resource.Layout.dialog_achievements = BestSellers.Droid.Resource.Layout.dialog_achievements;
			Android.Dialog.Resource.Layout.dialog_boolfieldleft = BestSellers.Droid.Resource.Layout.dialog_boolfieldleft;
			Android.Dialog.Resource.Layout.dialog_boolfieldright = BestSellers.Droid.Resource.Layout.dialog_boolfieldright;
			Android.Dialog.Resource.Layout.dialog_boolfieldsubleft = BestSellers.Droid.Resource.Layout.dialog_boolfieldsubleft;
			Android.Dialog.Resource.Layout.dialog_boolfieldsubright = BestSellers.Droid.Resource.Layout.dialog_boolfieldsubright;
			Android.Dialog.Resource.Layout.dialog_button = BestSellers.Droid.Resource.Layout.dialog_button;
			Android.Dialog.Resource.Layout.dialog_datefield = BestSellers.Droid.Resource.Layout.dialog_datefield;
			Android.Dialog.Resource.Layout.dialog_fieldsetlabel = BestSellers.Droid.Resource.Layout.dialog_fieldsetlabel;
			Android.Dialog.Resource.Layout.dialog_floatimage = BestSellers.Droid.Resource.Layout.dialog_floatimage;
			Android.Dialog.Resource.Layout.dialog_html = BestSellers.Droid.Resource.Layout.dialog_html;
			Android.Dialog.Resource.Layout.dialog_labelfieldbelow = BestSellers.Droid.Resource.Layout.dialog_labelfieldbelow;
			Android.Dialog.Resource.Layout.dialog_labelfieldright = BestSellers.Droid.Resource.Layout.dialog_labelfieldright;
			Android.Dialog.Resource.Layout.dialog_multiline_labelfieldbelow = BestSellers.Droid.Resource.Layout.dialog_multiline_labelfieldbelow;
			Android.Dialog.Resource.Layout.dialog_onofffieldright = BestSellers.Droid.Resource.Layout.dialog_onofffieldright;
			Android.Dialog.Resource.Layout.dialog_panel = BestSellers.Droid.Resource.Layout.dialog_panel;
			Android.Dialog.Resource.Layout.dialog_root = BestSellers.Droid.Resource.Layout.dialog_root;
			Android.Dialog.Resource.Layout.dialog_selectlist = BestSellers.Droid.Resource.Layout.dialog_selectlist;
			Android.Dialog.Resource.Layout.dialog_selectlistfield = BestSellers.Droid.Resource.Layout.dialog_selectlistfield;
			Android.Dialog.Resource.Layout.dialog_textarea = BestSellers.Droid.Resource.Layout.dialog_textarea;
			Android.Dialog.Resource.Layout.dialog_textfieldbelow = BestSellers.Droid.Resource.Layout.dialog_textfieldbelow;
			Android.Dialog.Resource.Layout.dialog_textfieldright = BestSellers.Droid.Resource.Layout.dialog_textfieldright;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int dialog_BoolField = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int dialog_Button = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int dialog_DisclosureField = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int dialog_HtmlField = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int dialog_ImageLeft = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int dialog_ImageRight = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int dialog_LabelField = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int dialog_LabelPercentageField = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int dialog_LabelSubtextField = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int dialog_Panel = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int dialog_RadioButtonList = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int dialog_SliderField = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int dialog_Spinner = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int dialog_ValueField = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int text1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int text2 = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_html = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labelfieldbelow = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labelfieldright = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_multiline_labelfieldbelow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_onofffieldright = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_panel = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_root = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_selectlist = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_selectlistfield = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_textarea = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_textfieldbelow = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textfieldright = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ListItem = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Splash = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
